### ISSUE TITLE
libssh2 have committed support for HMAC-SHA-256 and HMAC-SHA-512 MACs

### ISSUE THREAD

**Issue by vszakats** [fingolfin/ssh-comparison#23]
It has been committed, but not out yet. Expected in the next release:
https://github.com/libssh2/libssh2/commit/a53cebba34e6cde2cd4cdc7daec593992cd47e21

**Comment by fingolfin** [comment]
That's not an issue, though. An issue would be if it was in a released version... And even then, I'd rather see a pull request with updated information ;-).

But thanks for the pointer, I'll at least update the page to reflect the latest release 1.6.0.
