### ISSUE TITLE
Add table for extensions (draft-ssh-ext-info)

### ISSUE THREAD

**Issue by matbech** [fingolfin/ssh-comparison#39]
It would be nice if a table for the extensions defined in draft-ssh-ext-info could be added.
https://tools.ietf.org/html/draft-ssh-ext-info

OpenSSH, Bitvise and SmartFTP have already implemented some extensions.

Also related to this PR: https://github.com/fingolfin/ssh-comparison/pull/38

**Comment by fingolfin** [comment]
Feel free to make a pull request -- basically, you need to extend `_data/proto_classes.yml` and add `comparision/extensions.html` (by copying and editing another file in that dir)... and... that should probably be it... I may have forgotten something.
