### ISSUE TITLE
Add golang details

### ISSUE THREAD

**Issue by jnewbigin** [fingolfin/ssh-comparison#44]
Hi,
It would be great if you could add the details of golang golang.org/x/crypto/ssh
I found out that it supports these kex
curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha1 diffie-hellman-group1-sha1
but not diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1

**Comment by fingolfin** [comment]
We'll see...

In the meantime, pull requests are highly welcome :)

**Comment by jnewbigin** [comment]
I'll see what I can do.

**Comment by jnewbigin** [comment]
https://github.com/fingolfin/ssh-comparison/pull/45
