### ISSUE TITLE
Add Twisted Conch

### ISSUE THREAD

**Issue by fingolfin** [fingolfin/ssh-comparison#81]
https://twistedmatrix.com/trac/wiki/TwistedConch

**Comment by adiroiban** [comment]
Hi @fingolfin is this repo still active?

I am asking since I saw a PR from June 2022 that was not answered.

I am one of the maintainers of Twisted Conch and I think I can help with this.

Very useful site :) Thanks for your work.

**Comment by fingolfin** [comment]
It is still active in the sense that I merge PRs, but currently I don't have time to do much else with it (and thus unfortunately many entries are outdated). Well, and I  also get tons of GitHub notifications per day and probably overlooked those from last June :-(. I've merged them now.

If you were to make a PR adding Twisted Conch that'd be cool :-)

**Comment by adiroiban** [comment]
PR at https://github.com/fingolfin/ssh-comparison/pull/99 :) Thanks again for the site.
